### ISSUE TITLE
Review of Project Plan

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#118]
- [x] Resource names of [Project Plan](https://github.com/bounswe/bounswe2020group2/wiki/Project-Plan) should be changed according to subgroups for Android, back end and front end development. 
- [ ] Tasks of future process should be updated after finding the plan of each subgroup out from its corresponding leader. 

**_Due Date: 02.11.2020 Monday @23.59_**

**Comment by asliayk** [comment]
I added new group members to the project plan and updated the resource names according to subgroups, will upload it after
we discuss the tasks of future processes also with other group members.

**Comment by asliayk** [comment]
- [x] I added new group members to our project plan.
- [x] I edited the resource names according to three subgroups.
- [x] I edited the dates for the tasks of this term. (shifted one month as this term has shifted)

**Comment by karalleyna** [comment]
Changing subtasks of the project was carried over the next week since merging the plan of each group was determined as an action item for Tuesday meeting.

**Comment by abdullahyldz** [comment]
The Assistant announced the milestone dates. 

**Milestone 1: 24.11.2020
Milestone 2: 29.12.2020
Final Milestone: 19.01.2021**

Should we ask each subgroup to have a new plan for their tasks to catch up with new dates?

**Comment by karalleyna** [comment]
We, all group, determined all tasks until Milestone 1 according to the feedback of @uguracar during yesterday's meeting. We adjusted the deadlines on Google Calendar, which will be transferred to Project Libre with their resources. So, we can close this issue since it is not our responsibility anymore.
