### ISSUE TITLE
Preparing Project Plan Part I

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#73]
- [x] Evaluation of class diagram
- [x] Review of Balsamiq
- [x] Review of Lucidchard
- [x] Personal effort part
- [x] Adding our logo
