### ISSUE TITLE
Preparing Some Parts of Milestone 1 Report

### ISSUE THREAD

**Issue by asliayk** [bounswe/bounswe2020group2#74]
- [x] Review of Excel
- [x] Evaluation of RAM
- [x] Evaluation of Scenarios&Mockups
- [x] Summary of personal work done

Deadline: 02.05.2020 @ 23:59

**Comment by asliayk** [comment]
added to milestone report draft.
